### ISSUE TITLE
O mapa não carrega direito.

### ISSUE THREAD

**Issue by Lufims** [pedrolecio/gta-brasil#7]
Preciso de ajuda com isso.

![ajuda](https://user-images.githubusercontent.com/73536178/181396340-e3782e83-2392-4eba-bd9f-1404c47b1658.png)
[CrashList.txt](https://github.com/pulse-club/gta-brasil/files/9204389/CrashList.txt)

Parece que é só com os modelos customizados em alta resolução.
![Screenshot_3](https://user-images.githubusercontent.com/73536178/181631613-1e7d48a1-11a9-4ff1-a55a-9a8d96d7e508.png)
![Screenshot_4](https://user-images.githubusercontent.com/73536178/181631627-dd7b0d99-5094-410a-836a-864de352d0fe.png)

**Comment by pedrolecio** [comment]
Instale o Mix Sets.
